// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7MvGkn5A61ZWsAvvg0KPEvg9-T7GjCuU',
    appId: '1:502551318671:web:f564da5c622712ddefe0fa',
    messagingSenderId: '502551318671',
    projectId: 'sharekhan-shivam.com',
    authDomain: 'sharekhan-shivam.com.firebaseapp.com',
    storageBucket: 'sharekhan-shivam.com.appspot.com',
    measurementId: 'G-Q5JZDXD1K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Bywti7zNk_qtnPc7v8Xqg87W5k0TKXU',
    appId: '1:502551318671:android:371387ec98518ff3efe0fa',
    messagingSenderId: '502551318671',
    projectId: 'sharekhan-shivam.com',
    storageBucket: 'sharekhan-shivam.com.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZx5hBNz4d27lYZXzOcu7txGczzR3i_5g',
    appId: '1:502551318671:ios:a387e48bed8ed21befe0fa',
    messagingSenderId: '502551318671',
    projectId: 'sharekhan-shivam.com',
    storageBucket: 'sharekhan-shivam.com.appspot.com',
    iosBundleId: 'com.example.shivamSharekhan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZx5hBNz4d27lYZXzOcu7txGczzR3i_5g',
    appId: '1:502551318671:ios:a387e48bed8ed21befe0fa',
    messagingSenderId: '502551318671',
    projectId: 'sharekhan-shivam.com',
    storageBucket: 'sharekhan-shivam.com.appspot.com',
    iosBundleId: 'com.example.shivamSharekhan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7MvGkn5A61ZWsAvvg0KPEvg9-T7GjCuU',
    appId: '1:502551318671:web:91459ec78a6898fdefe0fa',
    messagingSenderId: '502551318671',
    projectId: 'sharekhan-shivam.com',
    authDomain: 'sharekhan-shivam.com.firebaseapp.com',
    storageBucket: 'sharekhan-shivam.com.appspot.com',
    measurementId: 'G-CG9HV23MGD',
  );
}
